- name: "Remove ntpd"
  apt:
    name: ntp
    state: absent
    purge: yes

- name: "Install ntpdate"
  apt:
    name: ntpdate
    state: latest
  register: ntpdate

- name: "Run ntpdate once to sync clock (IPv6)"
  command: /usr/sbin/ntpdate {{ ntp_default_server_v6 }}
  when: ntpdate.changed and hostvars[inventory_hostname]['V6'] is defined
- name: "Run ntpdate once to sync clock (IPv4)"
  command: /usr/sbin/ntpdate {{ ntp_default_server_v4 }}
  when: ntpdate.changed and hostvars[inventory_hostname]['V6'] is not defined

- name: "Install cronjob to run ntpdate after reboot"
  template:
    src: cron.d/ntp.j2
    dest: /etc/cron.d/ntp

- name: "Install openntpd"
  apt:
    name: openntpd
    state: latest

- name: "Create /etc/default/openntpd"
  copy:
    content: 'DAEMON_OPTS="-s -f /etc/openntpd/ntpd.conf"'
    dest: /etc/default/openntpd
    owner: root
    group: root
    mode: 0644
  notify: restart openntpd

- name: "Create openntpd/ntpd.conf"
  template: src=ntpd.conf.j2 dest=/etc/openntpd/ntpd.conf mode=644 owner=root group=root
  notify: restart openntpd
