- name: "Add powerdns apt repository"
  apt_repository:
    repo: 'deb [arch=amd64] http://repo.powerdns.com/ubuntu jammy-auth-47 main'
    state: present
    filename: 'pdns.list'

- name: "Install pdns-server"
  apt:
    name:
      - pdns-server
      - pdns-backend-mysql
    state: latest

- name: "Install pdns.conf"
  template: src=pdns.conf.j2 dest=/etc/powerdns/pdns.conf
  notify: reload pdns

- name: "Start pdns"
  service: name=pdns state=started

