- name: "Install haproxy"
  apt:
    name: haproxy
    state: latest

- name: "Install haproxy defaults file"
  template: src=haproxy.default.j2 dest=/etc/default/haproxy

- name: "Install haproxy.cfg"
  template: src=haproxy.relay.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  when: profile == "relay"
  notify: restart haproxy

- name: "Start haproxy"
  service: name=haproxy state=started

