- name: "Install reprepro"
  apt:
    name: reprepro
    state: latest

- name: "Setup repository directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    /var/www/apt.ring.nlnog.net/HTML/deb/conf

- name: "Install distributions file"
  copy:
    src=distributions
    dest=/var/www/apt.ring.nlnog.net/HTML/deb/conf/distributions
    owner=root
    group=root
    mode=0644

- name: "Create .gnupg directory for user root"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    /root/.gnupg

- name: "Copy private key"
  template: src=priv.key.j2 dest=/root/.gnupg/priv.key
  register: privkey

- name: "Import private key"
  command: "gpg --homedir /root/.gnupg --import /root/.gnupg/priv.key"
  when: privkey.changed

- name: "Install deb2repo"
  copy:
    src=deb2repo
    dest=/usr/local/sbin/deb2repo
    owner=root
    group=root
    mode=0755
