---
- name: Ensure other nameservers are not installed
  apt:
    name:
      - bind9
      - pdns-recursor
    state: absent
    purge: true

- name: Disable systemd-resolved
  service: name=systemd-resolved state=stopped enabled=no

- name: Remove network-manager
  apt:
    name: network-manager
    state: absent

- name: Install unbound
  apt:
    name: "{{ item }}"
      - unbound
      - unbound-anchor
      - unbound-host
      - python3-unbound
      - libunbound8
    state: latest

- name: Configure unbound
  template:
    src: "unbound.conf.j2"
    dest: /etc/unbound/unbound.conf
  notify: reload unbound

- name: Start and enable unbound
  service:
    name: unbound
    state: started
    enabled: true

- name: Add /etc/resolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
