- hosts: ringnode:auth.infra.ring.nlnog.net
  become: true
  become_user: root
  tasks:
    - name: "Load user role variables"
      include_vars: roles/users/defaults/main.yml

    - name: "Load user class variables"
      include_vars: roles/users/vars/ring-users.yml

    - include_tasks: roles/users/tasks/user_tasks.yml
      vars:
        user: "{{ USERS[item] }}"
        item: "{{ username }}"

    - include_tasks: roles/users/tasks/user_tasks_auth.yml
      vars:
        user: "{{ USERS[item] }}"
        item: "{{ username }}"
      when: inventory_hostname == "auth.infra.ring.nlnog.net"

