- name: "Install library dependencies"
  apt:
    name:
      - libdpkg-perl
      - libgetopt-simple-perl
    state: latest

- name: "Ensure purgekernels apt.conf is absent"
  file:
    path=/etc/apt/apt.conf.d/88purgekernels
    state=absent

- name: "Install ring-fetch-nodes-json"
  copy:
    src=ring-fetch-nodes-json
    dest=/usr/local/bin/ring-fetch-nodes-json
    owner=root
    group=root
    mode=0755

- name: Add cronjob for ring-fetch-nodes-json
  template:
    src: "cron.d/ring-fetch-nodes-json.j2"
    dest: /etc/cron.d/ring-fetch-nodes-json

- name: "Install geotrshell"
  copy:
    src=geotrshell
    dest=/usr/local/bin/geotrshell
    owner=root
    group=root
    mode=0755

- name: "Install intraceshell"
  copy:
    src=intraceshell
    dest=/usr/local/bin/intraceshell
    owner=root
    group=root
    mode=0755

- include_tasks: dbmaster.yml
  when: dbmaster == true

- include_tasks: pdnsmaster.yml
  when: pdnsmaster == true

