- name: "Install deb prerequisites for ripe-atlas-tools"
  apt:
    name:
      - libffi-dev
      - libssl-dev
      - virtualenv
    state: present

- name: "Install deb prerequisites for ripe-atlas-tools"
  apt:
    name:
      - python3-dev
      - python3-virtualenv
      - python3-pip
    state: present

- name: "Install ripe-atlas-tools"
  pip:
    name:
      - IPy
      - pyOpenSSL
      - ndg-httpsclient
      - pyasn1
      - 'git+https://github.com/RIPE-NCC/ripe-atlas-tools@latest#egg=ripe-atlas-tools'
    state: present
    virtualenv: "{{ ripe_atlas_venv_dir }}"
    virtualenv_python: python3

- name: "Create symlinks for ripe-atlas-tools"
  file:
    state: link
    force: true
    src: "{{ ripe_atlas_venv_dir }}/bin/{{ item }}"
    path: "/usr/local/bin/{{ item }}"
  with_items:
    - adig
    - ahttp
    - antp
    - aping
    - asslcert
    - atraceroute
    - ndg_httpclient
    - ripe-atlas
    - wsdump.py
