- name: "Install update-motd"
  apt:
    name: update-motd
    state: latest

- name: "Remove uninteresting motd items"
  file: path={{ item }} state=absent
  with_items:
    - /etc/update-motd.d/20-cpu-checker
    - /etc/update-motd.d/91-release-upgrade

- name: "Add motd scripts"
  copy:
    src={{ item }}
    dest=/etc/update-motd.d/{{ item }}
    owner=root
    group=root
    mode=0755
  with_items:
    - 50-landscape-sysinfo
    - 60-node-information

- name: "Add other motd files"
  copy:
    src={{ item }}
    dest=/etc/update-motd.d/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - ring.nlnog.net-logo

- name: "Add update-motd cronjob"
  cron:
    name: update_motd
    job: run-parts --lsbsysinit /etc/update-motd.d > /var/run/motd 2>/dev/null
    hour: 1,7,13,19
    minute: '15'
    user: root

- name: "Check for motd-news"
  stat: path=/etc/default/motd-news
  register: etc_default_motd_news

- name: "Disable the News MOTD line"
  lineinfile:
    path: /etc/default/motd-news
    regexp: '^ENABLED='
    line: 'ENABLED=0'
    owner: root
    group: root
    mode: 0644
  when: etc_default_motd_news.stat.exists == True
