- name: "Install openssh-server"
  apt:
    name: openssh-server
    state: latest

- include: ringnode.yml
  when: "'ringnode' in group_names"

- include: infranode.yml
  when: "'infranode' in group_names"

