---
# local service user
- include_tasks: user.yml
  when: kafka_configure_broker or kafka_configure_zookeeper

# download + unpack kafka
- include_tasks: install.yml
  when: kafka_configure_broker or kafka_configure_zookeeper

# Kafka configs
- include_tasks: kafka.yml
  when: kafka_configure_broker

- include_tasks: zookeeper.yml
  when: kafka_configure_zookeeper
