- name: "Ensure /etc/ring exists"
  file:
    name: /etc/ring
    state: directory
    mode: 0755
    owner: root
    group: root

- name: "Ensure the hostname is set in /etc/hostname"
  copy:
    dest: /etc/hostname
    content: "{{ inventory_hostname }}"

- name: "Install dbus for systemd hostname changes"
  apt:
    name: dbus
    state: latest

- name: "Ensure systemd-hostnamed.service.d exists"
  file:
    name: /etc/systemd/system/systemd-hostnamed.service.d
    state: directory
    mode: 0755
    owner: root
    group: root

- name: "Install hostnamed override.conf"
  copy:
    src=hostnamed_override.conf
    dest=/etc/systemd/system/systemd-hostnamed.service.d/override.conf
    owner=root
    group=root
    mode=0644
  notify: reload systemd

- name: "Reload systemd if needed"
  meta: flush_handlers

- name: "Ensure the hostname is set"
  hostname:
    name: "{{ inventory_hostname }}"

- name: "Add /etc/rc.local"
  template:
    src: rc.local.j2
    dest: /etc/rc.local

- name: "Generate /etc/hosts"
  template: src=hosts.j2 dest=/etc/hosts

- name: "Update /etc/ssh/ssh_known_hosts"
  copy:
    src=ssh_known_hosts
    dest=/etc/ssh/ssh_known_hosts
    owner=root
    group=root
    mode=0644

- name: "Add upstart-job"
  copy:
    src=upstart-job
    dest=/lib/init/upstart-job
    owner=root
    group=root
    mode=0755

- name: "Disable multiarch"
  file:
    path: /etc/dpkg/dpkg.cfg.d/multiarch
    state: absent

- name: "Update /etc/bash.bashrc"
  copy:
    src=bash.bashrc
    dest=/etc/bash.bashrc
    owner=root
    group=root
    mode=0644

- name: "Update pam configuration"
  copy:
    src=pam_{{ item }}
    dest=/etc/pam.d/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - atd
    - cron
    - login
    - sshd
    - su
    - common-auth

- name: "Set localtime"
  file:
    src: /usr/share/zoneinfo/UTC
    dest: /etc/localtime
    state: link
    force: true

- name: "Update timezone file"
  copy:
    src=timezone
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644

- name: "Remove non-default root-anchor"
  file:
    path=/opt/root-anchor
    state=absent

- name: Add cronjob to update /etc/ring/ring-nodes.txt
  template:
    src: cron.d/list_ring_nodes.j2
    dest: /etc/cron.d/list_ring_nodes

- name: "Update /etc/adduser.conf"
  copy:
    src=adduser.conf
    dest=/etc/adduser.conf
    owner=root
    group=root
    mode=0644

- name: "Ensure symlink to dynamic motd exists"
  file:
    src: /var/run/motd
    dest: /etc/motd
    owner: root
    group: root
    state: link
    force: yes

- name: "Update /etc/smartd.conf"
  copy:
    src=smartd.conf
    dest=/etc/smartd.conf
    owner=root
    group=root
    mode=0644
  register: smartd_conf

- name: "Check if smartmontools is installed"
  package:
    name: smartmontools
    state: present
  check_mode: true
  register: smartmontools_installed
  when: smartd_conf.changed

- name: "Restart smartmontools if needed"
  command: /bin/true
  notify: restart smartmontools
  when: smartd_conf.changed and not smartmontools_installed.changed

- name: "Install cron if needed"
  apt:
    name: cron
    state: latest

- name: "Update /etc/cron.weekly/fstrim"
  copy:
    src=fstrim
    dest=/etc/cron.weekly/fstrim
    owner=root
    group=root
    mode=0755
