- block:
  - name: "Load user class variables"
    include_vars: "{{ class }}.yml"

  - name: "Add groups for class {{ class }}"
    group:
      name: "{{ item.key }}"
      state: "{{ item.value.state | default('present') }}"
      gid: "{{ item.value.gid }}"
    with_dict: "{{ GROUPS }}"

  - name: "Set up sudo access"
    lineinfile:
      dest: /etc/sudoers
      regexp: '^%{{ item.key }}'
      line: '%{{ item.key }} ALL=(ALL) NOPASSWD: ALL'
      state: "{% if item.value.sudo | default(False) | bool() %}present{% else %}absent{% endif %}"
    with_dict: "{{ GROUPS }}"

  - include_tasks: user_tasks.yml
    vars:
      user: "{{ USERS[item] }}"
    with_items: "{{ USERS|default([])|list|sort }}"

  - include_tasks: user_tasks_auth.yml
    vars:
      user: "{{ USERS[item] }}"
    with_items: "{{ USERS|default([])|list|sort }}"
    when: inventory_hostname == "auth.infra.ring.nlnog.net"
  when: class != "local" 

- block:
  - include_tasks: user_tasks_pdns.yml
    vars:
      user: "{{ USERS[item] }}"
    with_items: "{{ USERS|default([])|list|sort }}"
    when: inventory_hostname == "public03.infra.ring.nlnog.net"
  when: class == "ring-admins"

- block:
  - name: "Add local groups"
    group: name={{ item }} state={{ LOCAL_GROUPS[item] }}
    with_items: "{{ LOCAL_GROUPS|default([])|list }}"

  - include_tasks: user_tasks.yml
    vars:
      user: "{{ LOCAL_USERS[item] }}"
    with_items: "{{ LOCAL_USERS|default([])|list }}"
  when: class == "local"

