- name: install nftables
  apt:
    name: nftables
    state: latest

- name: nftables config
  template: src=nftables.conf.jinja dest=/etc/nftables.conf validate='/usr/sbin/nft -c -f %s'
  notify: reload nftables

- name: enable nftables
  service: name=nftables enabled=yes state=started
