- name: "Prepare /var/run/fail2ban"
  file: path=/var/run/fail2ban state=directory

- name: "Install fail2ban"
  apt:
    name: fail2ban
    state: latest

- name: "Install jail.local"
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local
  notify:
    - restart fail2ban

- file: name={{ item }} state=absent
  with_items:
    - /etc/fail2ban/jail.d/defaults-debian.conf

- name: "Install sshd.conf"
  copy:
    src=sshd.conf
    dest=/etc/fail2ban/jail.d/sshd.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart fail2ban

- name: "Install jail.conf"
  copy:
    src=jail.conf
    dest=/etc/fail2ban/jail.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart fail2ban

- name: "Enable fail2ban service"
  service:
    name: fail2ban
    enabled: yes
    state: started

