- name: "Install packages"
  apt:
    name:
      - ring-python-ceres
      - ring-python-whisper
      - ring-carbon
      - ring-python-graphite-web
    state: latest

- name: "Create graphite group"
  group:
    name: graphite
    state: present

- name: "Create carbon user"
  user:
    name: carbon
    comment: "Graphite - Carbon user"
    shell: /bin/false
    home: /opt/graphite
    groups: graphite
    state: present

- name: "Check if user www-data exists"
  getent: database=passwd key=www-data
  register: www_user_exists

- name: "Add www-data to graphite group"
  user:
    name: www-data
    groups: graphite
  when: www_user_exists is defined

- name: "Create graphite_storage directory"
  file:
    path: /opt/graphite/storage
    state: directory
    owner: root
    group: graphite
    mode: 0774

- name: "Set graphite.db permissions"
  file:
    path: /opt/graphite/storage/graphite.db
    owner: root
    group: graphite
    mode: 0660

- name: "Set graphite log permissions"
  file:
    path: /opt/graphite/storage/log
    state: directory
    owner: root
    group: graphite
    mode: 0774
    recurse: yes

- name: "Install carbon aggregation-rules.conf"
  copy:
    src=aggregation-rules.conf
    dest=/opt/graphite/conf/aggregation-rules.conf
    mode=0644
  notify: reload carbon

- name: "Install carbon blacklist.conf"
  copy:
    src=blacklist.conf
    dest=/opt/graphite/conf/blacklist.conf
    mode=0644
  notify: reload carbon

- name: "Install carbon carbon.amqp.conf"
  copy:
    src=carbon.amqp.conf
    dest=/opt/graphite/conf/carbon.amqp.conf
    mode=0644
  notify: reload carbon

- name: "Install carbon dashboard.conf"
  copy:
    src=dashboard.conf
    dest=/opt/graphite/conf/dashboard.conf
    mode=0644
  notify: reload carbon

- name: "Install carbon graphTemplates.conf"
  copy:
    src=graphTemplates.conf
    dest=/opt/graphite/conf/graphTemplates.conf
    mode=0644
  notify: reload carbon

- name: "Install carbon relay-rules.conf"
  copy:
    src=relay-rules.conf
    dest=/opt/graphite/conf/relay-rules.conf
    mode=0644
  notify: reload carbon

- name: "Install carbon rewrite-rules.conf"
  copy:
    src=rewrite-rules.conf
    dest=/opt/graphite/conf/rewrite-rules.conf
    mode=0644
  notify: reload carbon

- name: "Install carbon storage-aggregation.conf"
  copy:
    src=storage-aggregation.conf
    dest=/opt/graphite/conf/storage-aggregation.conf
    mode=0644
  notify: reload carbon

- name: "Install carbon storage-schemas.conf"
  copy:
    src=storage-schemas.conf
    dest=/opt/graphite/conf/storage-schemas.conf
    mode=0644
  notify: reload carbon

- name: "Install carbon whitelist.conf"
  copy:
    src=whitelist.conf
    dest=/opt/graphite/conf/whitelist.conf
    mode=0644
  notify: reload carbon

- name: "Install graphite.wsgi"
  copy:
    src=graphite.wsgi
    dest=/opt/graphite/conf/graphite.wsgi
    mode=0644

- name: "Install carbon.conf"
  template:
    src=carbon.conf.j2
    dest=/opt/graphite/conf/carbon.conf
    mode=0644
  notify: reload carbon

- name: "Install graphiteweb settings file"
  template:
    src=local_settings.py.j2
    dest=/opt/graphite/webapp/graphite/local_settings.py
    mode=0644

- name: "Start carbon"
  service: name=carbon state=started

- name: "Install ring-graphite admin tool"
  copy:
    src=ring-graphite
    dest=/usr/local/bin/ring-graphite
    mode=0755

- name: "Add graphite user import cronjob"
  template:
    src: cron.d/import_graphite_users.j2
    dest: /etc/cron.d/import_graphite_users

