- name: "Install library dependencies"
  apt:
    name:
      - libjson-perl
      - libwww-curl-perl
    state: latest

- name: "Make sure site_ruby directory exists (for ring.rb)"
  file:
    path: /usr/local/lib/site_ruby
    state: directory
    mode: 0755

- name: "Install ring.rb"
  copy:
    src=ring.rb
    dest=/usr/local/lib/site_ruby/ring.rb
    owner=root
    group=root
    mode=0755

- name: "Install net-ssh (for ring.rb)"
  gem: name=net-ssh executable=/usr/bin/gem user_install=no

- name: "Install ring-all net-ssh dependencies"
  apt:
    name:
      - ruby-ed25519
      - ruby-bcrypt-pbkdf
    state: latest

- name: "install ruby-rbnacl"
  apt:
    name: ruby-rbnacl
    state: latest

- name: "Install python3 modules for ring-mtr"
  pip:
    name:
      - dnspython==2.2.1
      - setuptools
      - wheel
      - parallel-ssh
    state: present
    executable: pip3

- name: "Install ring userscripts"
  copy:
    src={{ item }}
    dest=/usr/local/bin/{{ item }}
    owner=root
    group=root
    mode=0755
  with_items:
    - generate-hosts.py
    - ring-all
    - ring-all-serial
    - ring-curl
    - ring-http
    - ring-ping
    - ring-mtr
    - ring-trace
    - ring-uping

