- name: "Update ringfpingd.conf"
  template:
    src: ringfpingd.conf.j2
    dest: /etc/ringfpingd.conf
    owner: root
    group: root
    mode: 0600
  notify: restart ringfpingd

- name: "Install ringfpingd package"
  apt:
    name: ringfpingd
    state: latest
  notify: restart ringfpingd

# Stop ringfpingd until we have a replacement for Graphite
- name: "Make sure ringfpingd is running"
  service:
    name: ringfpingd
    state: stopped

